config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'contact/index'
  get 'friend/index'
  get 'test/index'
  get 'dashboard/index'
  get 'users/password'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/addbill_controller.rb
class AddbillController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

end

app/controllers/friend_controller.rb
class FriendController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      #asdjd.add
  end

end

app/controllers/passwords_conroller.rb
class PasswordsController < Devise::PasswordsController  
end 

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController  
	respond_to :json
  def after_sign_in_path_for(resource)
    dashboard_index_path
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController  
	respond_to :json
  def after_sign_in_path_for(resource)
    dashboard_index_path
  end


end  

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/addbill_helper.rb
module AddbillHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
      :user
    end

    def resource
      @resource ||= User.new
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/contact/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Dashboard</title>
      
    <!-- Bootstrap core CSS -->
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">
      
    <!-- Bootstrap Scripts -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDr4hv3W_J8l6nID8mdG1YXMBbWa6YbBkA&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
  </head>
    
  <body id="page-top">
      
  <!-- Page Wrapper -->
  <div class="active" id="wrapper">
      
  <!-- Sidebar -->
      <%= render "dashboard/sidebar" %>
  <!-- End of Sidebar -->
      
  <!-- Profile bar -->            
      <%= render "dashboard/profilebar" %>
  <!-- End of Profile bar -->
      
  <!-- Main Content -->
      <div id="content">
          
  <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

  <!-- Topbar -->
      <%= render "dashboard/navbar" %>
  <!-- End of Topbar -->
    
  <!-- Begin Page Content -->
      <div class="container-fluid">
        
  <!-- Content Row -->
    <br/><br/><br>
    <div class="row">
        <div class="contact-bg" style="">    
            <p style="margin-left: 25px;margin-top: 20px; color: rgba(255, 255, 255, 0.98);font-family: Raleway; font-weight: 700;">CONTACT</p>
            <p style="margin-left: 250px;margin-top: 30px; color: rgba(255, 255, 255, 0.8);font-family: Raleway; font-weight: 500;">805 Veterans Blv<br/> Sute 322 <br/>Redwood city, CA 94063</p> 
             <p style="margin-left: 500px;margin-top:-75px; color: rgba(255, 255, 255, 0.8);font-family: Raleway; font-weight: 500;"><i class="fa fa-mobile" style="padding-right: 5px;"></i> 415-201-93-34 <br/><i class="fa fa-envelope" aria-hidden="true" style="padding-right: 5px;"> </i>hellow@34gment.com</p>
        </div> 
    </div>
    <!-- Content Row -->

    <!-- Content Row -->
  
   <div class="row" style="margin-left: 23.8%; background-color: rgba(0, 0, 0, 0.1); width: 77%; height: 335px;">
       <div class="col-6" style="margin-top: 10px;">
        <form>
            <div class="form-group">
                <input type="text" class="form-control" Placeholder="Name"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Email" />
            </div>
            <textarea class="form-control" rows="5" id="comment" placeholder="Message"></textarea>
            <button type="submit" class="btn btn-warning rounded-pill" style="padding: 3px 3px 3px 3px; width: 100px; font-size: 14px; background-color: rgba(244, 165, 35, 1); font-family: Roboto; font-weight: 700; color: rgba(0, 0, 0, 0.98);float: right; margin-top: 11px;">SUMBIT</button>
           </form>
           </div>
       <div class="col-6" style="">
           
        
           <div id="cont-map"></div>
           
    </div>
        
    

    </div>
        </div>
    <!-- /.container-fluid -->
    
    </div>
    <!-- End of Main Content -->
        
    <!-- Footer -->

      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->
         <footer class="sticky-footer bg-light" style="position:fixed; width: 100%;  flex-shrink: 0; padding: 10px; object-position: bottom;bottom: 0px; background-color: rgba(241, 241, 241, 1);">
            <div class="container my-auto">
              <div class="copyright text-center my-auto" style="color: rgba(0, 0, 0, 1); font-family: Raleway; font-weight: 400; font-size: 13px;">
                <span style="float: left; margin-left: -95px;">Privacy and terms</span>
                <span style="float: right; margin-right: -95px;">&#169; 2013-2016 . All rights reserved.</span>
              </div>
            </div>
          </footer>
  </div>
  <!-- End of Page Wrapper -->
      

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
      <!-- map -->
    <script>
      // Initialize and add the map
      function initMap() {
        // The location of Uluru
        const uluru = { lat: -25.344, lng: 131.036 };
        // The map, centered at Uluru
        const map = new google.maps.Map(document.getElementById("cont-map"), {
          zoom: 4,
          center: uluru,
        });
        // The marker, positioned at Uluru
        const marker = new google.maps.Marker({
          position: uluru,
          map: map,
        });
      }   
        

    </script>
      
  </body>
  </html>

app/views/dashboard/_navbar.html.erb
<!-- ----------------------------------------Top Bar--------------------------------------------- -->

<nav class="navbar navbar-expand-lg navbar-dark " id="com-topbar">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#"> 
        <p id="topbar-brand">
            <span class="topbar-s">$</span>
            <span class="topbar-plitter">plitter</span>
        </p>
            <span Class="topbar-split" style="position: relative;">SPLIT IT UP</span>
    </a>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="#">
                <%= image_tag("/assets/dashboard/add_Bill.png", alt: "add_Bill", id: "add-bill") %>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <span><%= image_tag("/assets/dashboard/notification.png", alt: "notification", id: "notify") %></span>
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
        </li>
            <li class="nav-item">
                <%= link_to( destroy_user_session_path, :method => :delete) do %>
                    <%= image_tag("/assets/dashboard/logout.png", alt: "logout", id: "topbar-logout") %>
                <% end %>
            </li>
    </ul>
</nav> 

app/views/dashboard/_profilebar.html.erb
<!-- ----------------------------------PROFILE BAR---------------------------------------- -->
<nav id="com-profile" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
    <div class="sidebar-sticky pt-3">
        <div class="carousel-item active">
            <%= image_tag("/assets/dashboard/profile_image.png", alt: "profile pic", id: "com-profile-img", height: "110%", width: "110%") %>
            <div class="carousel-caption">
                <%= image_tag("/assets/dashboard/Settings.png", alt: "settings", id: "com-pro-settings", "data-toggle": "modal", "data-target": "#setting-up-modal") %>
            </div>
            <div class="carousel-caption" id="com-pro-caption">
                <h3 id="pfname">Dorothy </h3>
                <h3 id="plname">Marian Davis</h3>
            </div>   
        </div>
    </div>
    
    <!-- Balence Details -->
    <br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <div class="sidebar-heading" id="summary">
        SUMMARY
    </div>
    
    <hr class="sidebar-divider" id="sum-div">     
        <div class="left">
            <p id="D-amt">$250</p>
            <p id="D-text">Debit</p>
        </div>
        <div class="right">
            <p id="C-amt">$350</p>
            <p id="C-text">Credit</p>
        </div>
    
    <hr class="sidebar-divider" id="sum-hr">
        <p id="B-next">
            <span id="B-text">Balance</span><span id="B-amt">- $100</span>
        </p>
        <hr class="sidebar-divider" id="B-hr">
        <div class="left">
            <p id="frnds-no">250</p>
            <p id="frnds-no-text">Friends</p>
        </div>
        <div class="right2">
            <p id="bill-no">350</p>
            <p id="bill-no-text">Bills</p>
        </div>
    
    <hr id="invite-hr"class="sidebar-divider">
        <div class="sidebar-heading" id="invite-form">
            INVITE A NEW FRIEND
        </div>
        <form>
            <div class="form-group">
                <input type="text" class="form-control" id="invite-name" Placeholder="Name"/>
             </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Enter his/her email ID" id="invite-email"/>
            </div>
            <%= image_tag("/assets/dashboard/send_button.png", alt: "btn", id: "invite-btn", type: "button") %>
        </form>
</nav>
<%= render "dashboard/settings" %>

app/views/dashboard/_settings.html.erb
<!-- ---------------------------------------PROFILE SETTINGS---------------------------------- -->
    <div class="modal fade" id="setting-up-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color: rgba(52, 83, 130, 1);">
                    <h5 class="modal-title" id="settle-up-header">SETTINGS</h5>
                     <%= image_tag("/assets/settle_up/Close_white.png", alt: "close", class: "close", "data-dismiss": "modal", "arial-label": "Close", "aria-hidden": "true") %>
                  <!--  <img src="assets/images/" alt="close" type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true"> -->
                </div>
                <div class="modal-body" style="background-color: rgba(242, 242, 242, 1);">
                    <p style="font-family: Raleway; font-weight: 700;">Change Your Profile Photo</p><hr>
                    <form name="newad" method="post" enctype="multipart/form-data" action="">
                        <table>
                        <img style=" display: block; margin-left: auto; margin-right: auto;" src="upload2/avatar.png" width="200" height="200" />
                        <tr><td><input type="file" name="image" ></td></tr>
                        <tr><td><input name="Submit" type="submit" value="Upload image"></td></tr>
                        </table>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Save</button>
                </div>
            </div>
        </div>
    </div>

app/views/dashboard/_sidebar.html.erb
<!-- --------------------------------SIDEBAR-------------------------------- -->

<nav id="dash-sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
    <div class="sidebar" id="dash-sidebar">
        <ul class="nav flex-column">
            <li class="nav-item">
                <%= link_to dashboard_index_path do %>
                    <br/>
                    <%= image_tag("/assets/dashboard/dashboard_icon_active.png", alt: "dash-icon", id: "dash-icon-act") %>
                    <p class="dash" id="dash-text">
                    DASHBOARD 
                    </p>
                <% end %><hr id="dash-hr" />
            </li>
            
            <li class="nav-item">
                <%= link_to friend_index_path do %>
                    <%= image_tag("/assets/dashboard/friend_icon.png", alt: "fnd-icon", id: "dash-fnd-icon") %>
                    <p class="dash" id="dash-fnd-text">
                    FRIENDS
                    </p>
                <% end %><hr id="dash-frnd-hr" />
            </li>
            
            <li class="nav-item">
                <%= link_to contact_index_path do %>
                    <%= image_tag("/assets/dashboard/Contact_icon.png", alt: "cont-icon", id: "dash-cont-icon") %>
                    <p class="dash" id="dash-cont-text">
                    CONTACT
                    </p>
                <% end %><hr id="dash-cont-hr" />
            </li>
        </ul>
    </div>
</nav>

app/views/friend/_fndsidebar.html.erb
<!-- --------------------------------SIDEBAR-------------------------------- -->

<nav id="dash-sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
    <div class="sidebar" id="dash-sidebar">
        <ul class="nav flex-column">
            <li class="nav-item">
                <%= link_to dashboard_index_path do %>
                    <br/>
                    <%= image_tag("/assets/friend/dash_board_icon_not_active.png", alt: "dash-icon", id: "dash-icon-act") %>
                    <p class="dash" id="dash-text">
                    DASHBOARD 
                    </p>
                <% end %><hr id="dash-hr" />
            </li>
            
            <li class="nav-item">
                <%= link_to friend_index_path do %>
                    <%= image_tag("/assets/friend/friend_icon_active.png", alt: "fnd-icon", id: "dash-fnd-icon") %>
                    <p class="dash" id="dash-fnd-text">
                    FRIENDS
                    </p>
                <% end %><hr id="dash-frnd-hr" />
            </li>
            
            <li class="nav-item">
                <%= link_to contact_index_path do %>
                    <%= image_tag("/assets/dashboard/Contact_icon.png", alt: "cont-icon", id: "dash-cont-icon") %>
                    <p class="dash" id="dash-cont-text">
                    CONTACT
                    </p>
                <% end %><hr id="dash-cont-hr" />
            </li>
        </ul>
    </div>
</nav>  

app/views/home/_login.html.erb
<!-- The Modal Login -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" id="login-dialog">
            <div class="modal-content" id="login-content" >
                <div class="row">
                    <div class="col-sm-4" id="log-col-4">
                        <div id="ls-reg-Modal">
                            <p id="log-brand">
                                <span class="log-s">$</span>
                                <span class="log-plitter">plitter</span>
                            </p>
                            <span Class="log-split">SPLIT IT UP</span>
                        </div>
                    </div>
                   <div class="log-col6">
                        <%= image_tag("/assets/login/close.png", alt: "close", id: "modal-close", type: "button", class:"close", "data-dismiss":"modal") %>
                        <br/>
                        <p id="log-cont-header">LOGIN</p>
                        <p id="log-para-1">Dont have an account? <a href="#" data-toggle="modal" data-target="#registerModal" data-dismiss="modal" id="log-link1">Create your account,</a><br/>it takes less than a minute.</p>
                       <div class="login-form">
                        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                            <div id="errors" style="color: red;"></div>
                            <div class="form-group">
                                <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", id:"e-mail",  onchange:"hideIcon(this);", Placeholder:"Email"%>
                            </div>

                            <div class="form-group">
                                <%= f.password_field :password, autocomplete: "current-password", class:"form-control", id:"pwd",  onchange:"hideIcon(this);", Placeholder:"Password"%>
                            </div>
                          <div class="actions">
                            <%= f.submit "Login", class:"login btn btn-warning rounded-pill", id:"log-btn"%>
                          </div>
                        <% end %>
                            <p></p>
                            <%= link_to "Forgot password", edit_user_password_path, id:"log-link2" %>
                      <!--  <div class="login-form">
                            <form>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="e-mail" name="e-mail" onchange="hideIcon(this);" Placeholder="Email" />
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password" id="pwd" name="pwd" onchange="hideIcon(this);" Placeholder="Password" style=""/>
                                </div>
                                <button type="submit" class="btn btn-warning rounded-pill" id="log-btn">Login</button>
                            </form>
                            <p></p>
                            <a href="#" id="link2">Forgot password</a>  -->
                            <br/>
                            <p></p>
                            <br/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
<!-- End of Modal Login -->

app/views/home/_register.html.erb
<!-- Start of Modal Register -->
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" id="register-dialog">
            <div class="modal-content" id="register-content" >
                <div class="row">
                    <div class="col-sm-4" id="reg-col-4">
                        <div id="ls-reg-Modal">
                            <p id="reg-brand">
                                <span class="reg-s">$</span>
                                <span class="reg-plitter">plitter</span>
                            </p>
                            <span Class="reg-split">SPLIT IT UP</span>
                        </div>
                    </div>
                    <div class="reg-col6">
                        <%= image_tag("/assets/login/close.png", alt: "applestore_button", type: "button", id: "reg-modal-close", class:"close", "data-dismiss":"modal") %>
                        <br/>
                        <p id="reg-cont-header">REGISTER</p>
                        
                        <div class="login-form">
                            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                            <%= render "devise/shared/error_messages", resource: resource %>
                                <div class="form-group">
                                    <%= f.text_field :username, autofocus: true, autocomplete: "username", class:"form-control", id:"user",  onchange:"hideIcon(this);", Placeholder:"Name"%>
                                </div>
                                
                                <div class="form-group">
                                    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", id:"e-mail",  onchange:"hideIcon(this);", Placeholder:"Email"%>
                                </div>
                                
                                <div class="form-group">
                                    <%= f.text_field :phn_no, autofocus: true, autocomplete: "phn_no", class:"form-control", id:"phn",  onchange:"hideIcon(this);", Placeholder:"Phone number"%>
                                </div>
                                
                                <div class="form-group">
                                    <% if @minimum_password_length %>
                                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                                    <% end %>
                                    <%= f.password_field :password, autocomplete: "new-password", class:"form-control", placeholder:"Password", id:"pwd",  onchange:"hideIcon(this);", Placeholder:"Password" %>
                                </div>
                                
                                <div class="form-group">
                                    <%= f.password_field :password, autocomplete: "new-password", class:"form-control", id:"pwd",  onchange:"hideIcon(this);", Placeholder:"Confirm password" %>
                                </div>
                                <button type="submit" class="btn btn-warning rounded-pill" id="reg-btn">Sign Up</button>
                            <% end %>
                            <p></p>
                            <p id="reg-para1">If you already have an account,<a href="#" data-toggle="modal" data-target="#loginModal" data-dismiss="modal" id="reg-link"> just login.</a></p>
                            <br/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
<!-- End of Modal Register -->

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.image %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Image:</strong>
  <%= @profile.image %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>